### PR TITLE
chore: drop usage of npm

### PR DESCRIPTION
**Pull request by so1ve**
I would suggest not recommending using npm to install dependencies when pnpm is not installed too. That would cause some problems. Developers can simply run `corepack enable` if you have defined `packageManager` field in your `package.json`.

### CODE REVIEW

**Comment by lete114** [comment]
What is `corepack enable`?

**Comment by so1ve** [comment]
@Lete114 Enables corepack

It will read the `packageManager` field in your `package.json` and load it, thus you don't have to worry about not installing pnpm.

**Comment by lete114** [comment]
How does it work?

Assuming I don't have `pnpm` installed so I installed the dependency (npm i) using `npm`, would it force me to be using `pnpm`?

**Comment by so1ve** [comment]
If you don't run `corepack enable`, it won't force you to use the configured package manager. However, force using the same package manager can avoid many problems. So though we cannot use npm anymore, it's irrelevant.

**Comment by lete114** [comment]
But I don't have the `corepack` command in my device, what is it?

**Comment by so1ve** [comment]
Node 16 should bundle it out-of-box. Maybe you don't have environment variables configured correctly

**Comment by lete114** [comment]
It's just a template to help you build quickly, the user should make his own modifications as appropriate, he may be using `npm` or `yarn` or something else, I don't think we should require people to use `pnpm`.

**Comment by lete114** [comment]
> Node 16 should bundle it out-of-box. Maybe you don't have environment variables configured correctly

Do I still need to configure the environment for this? I haven't heard of this command, I'm using `nodejs18`, is this a bit too difficult to get started with for a quick build template?

**Comment by so1ve** [comment]
理论上来说如果你装了node18的话他应该和npm一样能直接用的啊…而且起手模板里头也不应该混用包管理吧，用户如果想换别的包管理在这个PR里头只需要全局替换字符串就行了，corepack不止能自动使用正确的包管理，还能强制使用指定的那个，反正混用问题很大 起手模板应该是opinionated的，没必要考虑到所有人的喜好 更何况`corepack enable`一下的事，用户也没什么负担

**Comment by lete114** [comment]
我的提示没有这个命令corepack

**Comment by lete114** [comment]
使用的是 powershell

**Comment by lete114** [comment]
node16 没有 corepack.ps

**Comment by so1ve** [comment]
> 使用的是 powershell

版本太低？

**Pull request merged**
